### PR TITLE
[dnm] chore: remove Node.js 4, add Node.js 10

### LINKED ISSUE #79: failing unit tests on Node.js 4
I'll probably investigate this but these should not fail. Not yet sure if this is due to the (dev)dependencies or other changes.

### PR DESCRIPTION
**Pull request by DanielRuf**
Closes #79

### CODE REVIEW

**Comment by DanielRuf** [comment]
See the following because of the failing Windows build: https://github.com/nodejs/node/issues/20297

**Comment by ev1stensberg** [comment]
@evilebottnawi should we add v10 anyways?

**Comment by evilebottnawi** [comment]
Looks we catch node 10.0.0 bug :laughing:

**Comment by evilebottnawi** [comment]
@ev1stensberg yep, we need add 10.0.0 in all webpack/webpack-contrib repos

**Comment by evilebottnawi** [comment]
Blocker https://github.com/nodejs/node/issues/20297. Using webpack and watch mode on nodejs 10.0.0 can't works as expected :disappointed:

**Comment by DanielRuf** [comment]
> webpack and watch mode

The watch mode is used on CI? Shouldn't this not be the case normally?

**Comment by evilebottnawi** [comment]
@DanielRuf here tests for watch systems

**Comment by DanielRuf** [comment]
> @DanielRuf here tests for watch systems

Ah ok, makes definitely sense 😃 Sorry.

**Comment by DanielRuf** [comment]
> @DanielRuf we need restart CI, node 10.1.0 release

Seems it is not yet available on Appveyor. Should I ping them?

**Comment by DanielRuf** [comment]
See https://github.com/nodejs/node/issues/20738

**Comment by sokra** [comment]
Thanks

**Pull request merged**
