### PR TITLE
Fix remove event is not emitted

### PR DESCRIPTION
**Pull request by nkzawa**
It looks we have to check if `mtime` exists.

### CODE REVIEW

**Comment by aesopwolf** [comment]
@sokra would you mind helping get this merged in? Another PR needs this to land before it can continue https://github.com/zeit/next.js/pull/222

**Comment by TheLarkInn** [comment]
@nkzawa Can you add a test for this if applicable.

**Comment by TheLarkInn** [comment]
https://github.com/webpack/watchpack/blob/master/test/DirectoryWatcher.test.js 

Can just check that code handles absence of mtimes.

**Comment by nkzawa** [comment]
Added a test.

**Comment by sokra** [comment]
Thanks

**Comment by aesopwolf** [comment]
npm publish?

**Comment by rauchg** [comment]
Thanks a lot @sokra. What's the process like to go from here to a published release?

**Pull request merged**
