### PR TITLE
Require Node.js 6.11.5 or newer

### PR DESCRIPTION
**Pull request by realityking**
This aligns with webpack 4.

### CODE REVIEW

**Comment by ooflorent** [comment]
@evilebottnawi Not an issue. `watchpack` is safe to bump.

**Comment by evilebottnawi** [comment]
@ooflorent for `webpack@4` is safe, but maybe other project use this library :confused:

**Comment by evilebottnawi** [comment]
Boom https://www.npmjs.com/browse/depended/watchpack

**Comment by evilebottnawi** [comment]
Need major release

**Comment by ooflorent** [comment]
> Need major release

Indeed, but the PR won't change.

**Comment by realityking** [comment]
Rebased to fix a merge conflict.

@evilebottnawi I had a look at that page before I opened this PR. The only other popular dependent package is `web-ext` and it's comparatively small with ~4000 weekly downloads. Since it already requires Node.js 6.0, I hope they'll up their requirements to 6.11.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
