### PR TITLE
Allow passing in a regex directly to "ignored"

### PR DESCRIPTION
**Pull request by marksamman**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA, also can you add tests?

**Comment by marksamman** [comment]
Signed the CLA, feel free to edit my branch to add tests before merging if you like.

**Comment by ypconstante** [comment]
It would be good to also allow 'ignored' to be an array of regexes, or an mixed array of regexes and strings.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
