### PR TITLE
chore(ignore): adds package-lock.json to gitignore

### PR DESCRIPTION
**Pull request by pranshuchittora**
Added `package-lock.json` to `gitignore`

### CODE REVIEW

**Comment by hiroppy** [comment]
Why?

**Comment by pranshuchittora** [comment]
Because we are using `yarn` in CI. And it's better to keep single lock file.

**Comment by hiroppy** [comment]
Yes, I know. So we only have to use yarn. There is no need to explicitly add package-lock.json to .gitignore.

**Comment by hiroppy** [comment]
If you are afraid that package-lock.json will be made,  we just write `package-lock=false` to `.npmrc`.

**Comment by pranshuchittora** [comment]
Sounds great, but what about someone committed `package-lock.json` by mistake. Prevention is better than cure.

**Comment by pranshuchittora** [comment]
@hiroppy pls check this out :point_down: 
https://github.com/webpack/webpack/blob/069271decf4a4513e174e73f6d49bf6113e8d892/.gitignore#L14

**Comment by sokra** [comment]
While you shouldn't create a package-lock.json file in the first place, because yarn should be used instead of `npm`, it doesn't hurt to have it ignored in gitignore for contributors that accidentally run npm.

**Pull request merged**
