### PR TITLE
watcherManager add fileSystem

### PR DESCRIPTION
**Pull request by yuchonghua**
1、exports WatcherManager
2、WatcherManager add fileSystem

### CODE REVIEW

**Comment by yuchonghua** [comment]
Automatic testing, not very likely to write, can you write it, thank you very much

**Comment by evilebottnawi** [comment]
@yuchonghua we need tests anyway

**Comment by sokra** [comment]
What's the reason for this change?

**Comment by yuchonghua** [comment]
Many times, for example, building on a development machine will be slower, and the development machine is most likely a window. At this time, I hope that the build is built on linux and then developed in the development server. At this time, WebSocket will be used to virtualize one. The file system is on webpack. At this time, the custom inputFileSystem is used, so it needs to be built by remote. At this time, we can no longer rely on the local graceful-fs. We expect the watchpack to support the custom file system just like webpack. thank you very much.
In fact, the method of implementing the remote file system has this reference [fs-remote](https://www.npmjs.com/package/fs-remote), but not only this

**Comment by yuchonghua** [comment]
> @yuchonghua we need tests anyway

Thank you very much for your enthusiasm and support, but I still don't write test at the moment. This pr is my own guess. I will try my best to study how the test is implemented. I also hope that you have a better solution. In fact, I just want to. To implement file system remote words, such as the old version depends on chokidar.watch, in fact, we can use the configuration of the chokidarWatch function, because I can provide a remote, chokidarWatch, also through the [WebSocket remote call](https://www.npmjs.com/package/run-on-server)

/ping @evilebottnawi

**Comment by sokra** [comment]
> At this time, the custom inputFileSystem is used, so it needs to be built by remote.

Have you considered also using a custom `watchFileSystem`. I guess that would be the cleaner solution.

**Comment by yuchonghua** [comment]
> > At this time, the custom inputFileSystem is used, so it needs to be built by remote.
> 
> Have you considered also using a custom `watchFileSystem`? I guess that would be the cleaner solution.
> 
> `Compiler.watchFileSystem`

Currently I have used the custom Compiler.watchFileSystem in my existing project, but I still look forward to the watchpack support, because I can rely on your package better, so you don't need to upgrade in webpack. When I re-maintain the Compiler.watchFileSystem, I am very grateful for your support, thank you
/ping @sokra

**Comment by yuchonghua** [comment]
Recently, it seems that ci-test is broken. Would you like to ask if there is any further maintenance in this library?
I am sorry, I am very much looking forward to the improvement of this library.

/ping @sokra

**Comment by sokra** [comment]
Thanks for your PR, but that's not an intended feature, as behavior is too tightly bound to node.js fs behavior.

**Pull request closed without merging**
