### PR TITLE
Update chokidar to 3.3.0

### LINKED ISSUE #130: Bring back chokidar v3
We've released Chokidar 3 in April. See my post on that: [Chokidar 3: How to save 32TB of traffic every week with one NPM package](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/)

The changes are pretty big. First of all, the package is 16 times smaller and uses 15 dependencies instead of 201. We've switched to n-api, which means users won't download fsevents binaries anymore. n-api is included in every nodejs installation, and it's tiny. Directory walking has been improved massively with stream implementation of readdirp. Massive RAM & CPU improvements etc.

I really suggest switching back to chokidar. You'll receive tons and tons of bug reports otherwise, since file watching is a complex task. You're using fs.watch — **it is unreliable** and doesn't solve the issue. For example, i've spent a couple days this week trying to fix race conditions appearing due to async nature of nodejs IO. That's why VS Code uses chokidar.

I can submit a pull request if you'll agree.

### PR DESCRIPTION
**Pull request by coreyward**
Regardless of what happens in watchpack 2.0.0, this fix will sidestep node-gyp issues for at least several hundred macOS Catalina users. The tests still turn up green w/o changes, but perhaps the coverage is poor? Fixes #130.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
It is breaking change

**Comment by coreyward** [comment]
@evilebottnawi Please provide a failing test. If you’re not willing to do the work to make this function I need to know where it fails.

**Comment by RDIL** [comment]
v3 requires at least node 8, maybe it is time to drop smaller versions?

**Comment by sokra** [comment]
> The tests still turn up green w/o changes

Installation fails to start on node 6, which seem to be expected as node 6 support was dropped.

But the tests are also failing on node 8 on linux and windows (not on mac). This is unexpected.

**Comment by sokra** [comment]
The problem seem to be caused by bugs in `readdirp`. These bugs are already fixed in a newer version. I was able to fix it locally by enforcing `readirp@3.4.0`, but this is not in the current range of chokidar. We need a new chokidar version pushing readdirp to 3.4.0. @paulmillr

**Comment by sokra** [comment]
hmm this fixes only the problems on linux. Windows is still broken on node.js 8

**Comment by paulmillr** [comment]
Pushing new chokidar is simple. What exactly is broken on node 8 @ windows? Hard to tell from tests.

**Comment by paulmillr** [comment]
BTW I suggest to switch to GitHub actions. It supports all three platforms.

**Comment by paulmillr** [comment]
Doesn't seem like the `close` method updated to use asynchronous chokidar.watcher.close - the only API change in chokidar 3. We've decided to adjust it because it's not possible to stop all IO syncronously.

See this pull request for reference: https://github.com/webpack/webpack-dev-server/pull/2539

**Comment by sokra** [comment]
> What exactly is broken on node 8 @ windows? Hard to tell from tests.

Not sure yet. Errors are weird.

On linux node 8 it also logs:

```
(node:5243) UnhandledPromiseRejectionWarning: TypeError: this._removeWatcher is not a function
    at DirEntry.remove (/home/travis/build/webpack/watchpack/node_modules/chokidar/index.js:161:14)
    at <anonymous>
(node:5243) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5243) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5243) UnhandledPromiseRejectionWarning: TypeError: this._removeWatcher is not a function
    at DirEntry.remove (/home/travis/build/webpack/watchpack/node_modules/chokidar/index.js:161:14)
    at <anonymous>
(node:5243) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

[remove seem to be an async method](https://github.com/paulmillr/chokidar/blob/1926fc7263b0ff3faa5622e935295c7a3c4988ce/index.js#L151) but none of its callsites handle the returned promise. Seems `remove` should handle the case that the DirEntry can be disposed duing the async `readdir` operation.

**Comment by sokra** [comment]
> Doesn't seem like the `close` method was updated to use asynchronous chokidar.watcher.close - the only API change in chokidar 3. We've decided to adjust it because it's not possible to stop all IO syncronously.

I added a `catch` handler there. The operation can continue in background, consumers of watchpack are not interested when the watcher is fully stopped. I assume it won't emit change events any longer once close has been called.

**Comment by sokra** [comment]
> > What exactly is broken on node 8 @ windows? Hard to tell from tests.
> 
> Not sure yet. Errors are weird.

I guess it's the `readdirp` thing. appveyor CI incorrectly runs npm install instead of yarn, which ignores the `resolutions` workaround I added.

**Comment by paulmillr** [comment]
Pushing 3.4 in a bit.

**Comment by paulmillr** [comment]
Is there any point in keeping old chokidar around? webpack-dev-server switched to v3 completely. You'll just keep seeing v2-related warnings.

**Comment by sokra** [comment]
> Is there any point in keeping old chokidar around?

Yep to not break semver. We must keep support for node.js 6 in this major version. As chokidar doesn't support node 6, we fallback to old chokidar for node 6.

These warnings seem to be a bit weird anyway. Why do you need to tell someone that it doesn't work for node 14 when they not using node 14 anyway? These warnings should only appear for node 14 users. Or even better would be if node 14 users get an error.

**Comment by paulmillr** [comment]
Because it can work. Or it can break. It doesn't always break. We've been receiving bug reports over and over regarding old versions. The amount of bug reports keeps getting increased for those. We need to make users upgrade at some point.

**Comment by surfaceowl** [comment]
@sokra 

> ...Why do you need to tell someone that it doesn't work for node 14 when they not using node 14 anyway? These warnings should only appear for node 14 users. 

I prefer the warnings so I can see potential problems in advance, rather than upgrading node and then discovering a branch won't build.

Also - chokidar bumped up to @v3.4.0 a few weeks ago, looks to be version bump on internal library for typing

https://www.npmjs.com/package/chokidar

**Comment by sokra** [comment]
Thanks

**Pull request merged**
