### PR TITLE
Run all code in strict mode

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by realityking** [comment]
Any news on this one?

**Comment by evilebottnawi** [comment]
@realityking Why?

**Comment by realityking** [comment]
@evilebottnawi It helps catching errors. It's also the default mode with EcmaScript modules so this will make sure the code is forward compatible.

Not a big gain but IMHO worth it.

**Comment by sokra** [comment]
Strict is always good 😀

**Comment by sokra** [comment]
Oh wait, this fails the CI...

**Comment by sokra** [comment]
fixed in #76

**Pull request merged**
