### PR TITLE
chore: remove Node.js 4 (EOL)

### LINKED ISSUE #79: failing unit tests on Node.js 4
I'll probably investigate this but these should not fail. Not yet sure if this is due to the (dev)dependencies or other changes.

### PR DESCRIPTION
**Pull request by DanielRuf**
Closes #79

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@DanielRuf Duplicate https://github.com/webpack/watchpack/pull/80?

**Comment by realityking** [comment]
Partially duplicates #64. I suspect it hasn't been merged yet to avoid a semver-major release.

**Comment by DanielRuf** [comment]
Hm, you are right. Oversaw this one. Should I close my PR then?

**Comment by realityking** [comment]
I slightly prefer mine because it adds the engine to package.json but I'm not the PR police 😆

**Pull request closed without merging**
